### PR TITLE
Andynuzzo/fix require cycles

### PR DESCRIPTION
**Pull request by andreanuzzo**
Changes to fix warnings in https://github.com/tripleblindmarket/private-kit/issues/54 

It uses a small post install patch, because the issue is from the native rn-fetch-blob package.

### CODE REVIEW

**Comment by vitorpamplona** [comment]
Thanks Andy! 

I was having issues with the: 
  implementation project(':@mauron85_react-native-background-geolocation')
line as well.

**Comment by vitorpamplona** [comment]
Question: whats that /patches directory?

**Comment by andreanuzzo** [comment]
Basically, the patch-packages package (!) makes the corrections to the rn-fetch-blob packages after running ‘yarn install’. Otherwise you have to correct them manually at every build, since the rn-fecth-blog original repo has not addressed the issues (an it’s sitting there since 2018).

**Comment by vitorpamplona** [comment]
Thanks for the clarification. Too bad they are not updating. 

I had to return these lines to the settings.graddle to compile. Were you able to run the Android version without them? 

Also, you might have to pull the updates from develop since there was a wrong version format in the packages.json file (my bad). 


include ':@mauron85_react-native-background-geolocation'
project(':@mauron85_react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/lib')
include ':@mauron85_react-native-background-geolocation-common'
project(':@mauron85_react-native-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/@mauron85/react-native-background-geolocation/android/common')

**Comment by penrods** [comment]
Abisheck had some issues when he tried this on his machine last night.  I'd like to get rid of the warning, but it isn't high priority.  Let's be really certain the patch technique works in all the cases.

Or better yet, let's find the maintainer and give them a shake! ;-)

**Comment by andreanuzzo** [comment]
I have run those only on the iOS simulator, because I had Xcode already installed. I am not a developer (and I mainly use python and R), I don’t have any experience with Android Studio. But since react-native should be cross-platform, you might be able to replicate the workflow through yarn patch-package. Follow the instructions here: 

https://blog.novanet.no/easier-react-native-upgrade-with-patch-package/

 

Andy

**Comment by vitorpamplona** [comment]
I got the Android app working. But the iOS doesn't recognize the AsyncStorage on my computer. 

The error only happens after the user starts logging the locations.

**Comment by andreanuzzo** [comment]
Fixed, it's the parenthesis. The app is logging gps data fine from this branch. 

https://github.com/andreanuzzo/private-kit/commit/ebe5bf7e8050e5c595edf24c9f281b3139d760b8

**Comment by vitorpamplona** [comment]
I included Andy's fixes and a few others on Branch 57. Can somebody check it out?

**Comment by vitorpamplona** [comment]
Closed on #67.

**Pull request closed without merging**
