### PR TITLE
Feature/new ui

### LINKED ISSUE #53: Pressing back from homescreen should exit the App
Right now the app goes back to the first Welcome screen if we press back. 
image

### PR DESCRIPTION
**Pull request by harshvitra**
The Welcome screens will only come when the user is not logging their information. 

Once the user starts logging information the back button will close the app - Fixes #53 #21 
Also fixes - #45

Screenshot_2020-03-17-20-35-05-654_edu mit privatekit
Screenshot_2020-03-17-20-37-16-415_edu mit privatekit
Screenshot_2020-03-17-20-37-25-268_edu mit privatekit
Screenshot_2020-03-17-20-37-27-515_edu mit privatekit
Screenshot_2020-03-17-20-37-29-759_edu mit privatekit

### CODE REVIEW

**Comment by tremblerz** [comment]
@vitorpamplona have you tested on both platforms?

**Comment by harshvitra** [comment]
### Screenshots from iOS - 

Simulator Screen Shot - iPhone 11 - 2020-03-17 at 22 09 59
Simulator Screen Shot - iPhone 11 - 2020-03-17 at 22 09 48
Simulator Screen Shot - iPhone 11 - 2020-03-17 at 22 09 33
Simulator Screen Shot - iPhone 11 - 2020-03-17 at 22 09 30
Simulator Screen Shot - iPhone 11 - 2020-03-17 at 22 09 26

**Comment by vitorpamplona** [comment]
Yes, it works on iOS as well.

**Comment by tremblerz** [comment]
let's merge but not release right now. I am looking at another potential bug in location logging, hasn't got to do anything with this pr

**Comment by harshvitra** [comment]
Designs for Export and Import Pages

Simulator Screen Shot - iPhone 11 - 2020-03-18 at 01 22 05
Simulator Screen Shot - iPhone 11 - 2020-03-18 at 01 21 59

**Comment by harshvitra** [comment]
Simulator Screen Shot - iPhone 11 - 2020-03-18 at 01 35 45

**Pull request merged**
