### PR TITLE
Hashing based private set intersection

### PR DESCRIPTION
**Pull request by tremblerz**
Performs sha256 -> geohashing
The front end is not implemented yet as we do not have "authorized download" or "self-reporting features"
For efficiency of the scheme, I would lean towards storing the hash at the same time when data is logged as it will save us from batched hashing of a file.

### CODE REVIEW

**Comment by tremblerz** [comment]
We gotta update the safe-paths branch with develop so that file changes are small

**Comment by rparet** [comment]
Goes with #144

**Comment by kenpugsley** [comment]
@tremblerz - I think this is likely a good candidate for something that we should first implement on the new private-kit repo.  Do you agree?

**Comment by tremblerz** [comment]
@kenpugsley agree. Anyway it looks like a mess right now with respect to the file changes. Closing

**Pull request closed without merging**
