### PR TITLE
SAF-804 clean up react-native-background-geolocation on android

### PR DESCRIPTION
**Pull request by tindn**
Apply the postinstall updates to the forked repo.

This should be merged together with https://github.com/Path-Check/react-native-background-geolocation/pull/3 and https://github.com/Path-Check/background-geolocation-android/pull/2 to reduce version mismatch errors

### CODE REVIEW

**Review by jvisenti — APPROVED** [review]
Let's merge the PRs in the Android submodule first. We'll then also need a PR against `react-native-background-geolocation` to update the submodule commit to latest. Once all 3 of those are merged we can merge this PR.

**Review by JacobJaffe — APPROVED** [review]
🎉 
image

**Review by johnschoeman — APPROVED** [review]
Nice!

**Comment by tindn** [comment]
@JacobJaffe , @johnschoeman , and @jvisenti , can you also help review the 2 other related PRs? This can't be merged until those are merged.

**Pull request closed without merging**
