### PR TITLE
Add locale picker, Haitian Creole translation

### PR DESCRIPTION
**Pull request by penrods**
Add a language picker on the first screen of the Welcome sequence.  This
allows nonstandard languages to be easily selected.

This is based on #355 by @StartupSam, but merged into the new UI

 ### Testing Notes ###

Start the welcome sequence after startup.  Select Haitian Creole (Angajman)

 ### Localization Notes ###

This adds Haitian Creole from Gerald

### CODE REVIEW

**Comment by harshvitra** [comment]
For others - Kreyòl Ayisyen (this is the label for Haitian Creole)

**Comment by harshvitra** [comment]
Content changes after language selection ! 

**Two things -** 
1. Once I'm inside the application (gone through the onboarding) there is no way to change the language. 
2. UI needs to be changed to match with the current designs

Screenshot_2020-04-06-15-26-47-292_edu mit privatekit

Screenshot_2020-04-06-15-29-32-927_edu mit privatekit

**Comment by penrods** [comment]
#368 will adjust those two issues on top of us, @harshvitra .

**Comment by StartupSam** [comment]
Actually @kenpugsley I think they're all fixed in the new PR now (but you should confirm ofc)

**Pull request merged**
