### PR TITLE
Color code in "PathCheck is saving the places" screen, issue #1119

### LINKED ISSUE #1119: Color code  in "PathCheck is saving the places" screen
UI issue
SamsungGalaxy S8 Emulator# Steps to reproduce
On the screen with the message "PathCheck is saving the Places..." there is an error message:

image

The color code contains "o" which should be "0".

### PR DESCRIPTION
**Pull request by crayne**
#### Description:

The color code for "porcelain" in colors.ts was incorrect

#### Linked issues:

Fixes #1119 

#### How to test:

In "PathCheck is saving the places" screen, there should be no error message about a color

### CODE REVIEW

**Comment by summetj** [comment]
What was the reason for the " "@types/semver": "^7.3.1"," change?

**Comment by crayne** [comment]
I did not make this change and don't know how it got in here.  I will attempt to remove it

**Comment by crayne** [comment]
Please don't review yet -- this is clearly not correct.

**Comment by summetj** [comment]
Don't be afraid to admit git defeat, remove this PR, check everything out again, fix the one thing, and issue a new PR....I've done that myself sometimes because it was easier than making changes to a PR ;>

**Comment by crayne** [comment]
I think I've fixed it now w/o making a new PR.  But if it isn't I will do what you suggest.

**Review by summetj — APPROVED** [review]
LGTM!

**Review by johnschoeman — APPROVED** [review]
LGTM, theres a know issue with the build CI for branches off of a fork.

We are working on it and we can merge this after that is resolved!

**Comment by crayne** [comment]
Thank you.

**Comment by johnschoeman** [comment]
further activity!

**Comment by crayne** [comment]
How do I go about fixing these failing tests?

**Comment by johnschoeman** [comment]
> How do I go about fixing these failing tests?

I'll merge this in on your behalf to get this across the finish line while we wait to get the env workflow polished up.

**Pull request merged**
