### PR TITLE
Updated iOS schemes

### PR DESCRIPTION
**Pull request by jvisenti**
#### Description:

Our current deployment strategy for iOS is manual and error prone. This PR cleans up existing build configurations and transitions the project to using xcconfig files. There are 2 release tracks (staging and production) that use different bundle identifiers and versioning. This also gives us the flexibility to install development, staging, and prod builds side-by-side on the same device, ideally with different icons in the future to disambiguate.

* Updated build configurations
* Use xcconfig files
* Removed unnecessary schemes

### CODE REVIEW

**Comment by jvisenti** [comment]
@johnschoeman I've updated the workflows so that they pass, but there is a new failing Build step that seems to be related to GCP. Does this need to be resolved before merge?

**Review by johnschoeman — APPROVED** [review]
Still looks good to me!

**Comment by johnschoeman** [comment]
> @johnschoeman I've updated the workflows so that they pass, but there is a new failing Build step that seems to be related to GCP. Does this need to be resolved before merge?

I'm not sure why this was added, but it seems odd to have a GCP thing in our CI for a mobile app, so I would say no.  I'll look into where this check came from.

**Review by JacobJaffe — APPROVED** [review]
Confirmed dev archive local succeeds! Thanks!

**Pull request merged**
