### PR TITLE
Update location notification

### PR DESCRIPTION
**Pull request by Shabanisimo**
Added check if geolocation tracking is turned off and the user navigates to the app that the notification is triggered once a certain period of time

### CODE REVIEW

**Comment by Patrick-Erichsen** [comment]
Hey @Shabanisimo - is this ready for review? If so, can you provide a description?

**Comment by Shabanisimo** [comment]
Description updated.

**Comment by Patrick-Erichsen** [comment]
So - I believe this will prevent users from receiving a notification every time that they turn location tracking off. Is that correct? 

If so, I'm not sure that's the behavior we want. I believe our intention is to push an alert every time that location tracking is stopped.

**Comment by Shabanisimo** [comment]
But with such frequent notifications, this can get annoying users.

**Pull request closed without merging**
