### PR TITLE
Request exposure notification authorization bt ios

### PR DESCRIPTION
**Pull request by johnschoeman**
Why:
We would like to use the exposure notification service provided by
apple in the application. In order to do so users must enable
authorization to the app. We would like to have this authorization
requested during the onboarding flow.

This commit:
Introduces a screen that will render in the BT app which will prompt the
user to enable Exposure Notifications. We introduced an
ExposureNotificationContext that contains the authorization state on the
js side and provides a way for components to request EN authorization by
calling into a Native Module which exposes a method for setting the
exposure notification to true in the iOS layer.

We also introduced the start of the Exposure Notification Service in the
BTE target and included the entitlements for Exposure Notifications.

Co-Authored-By: mattthousand <matt.buckley@rocketinsights.com>
Co-Authored-By: tparesi <thomas.paresi@thoughtbot.com>

#### iPhone

onboarding-en

### CODE REVIEW

**Comment by johnschoeman** [comment]
This one should be merged after: https://github.com/Path-Check/covid-safe-paths/pull/958

**Comment by johnschoeman** [comment]
now it should be merged after this one: https://github.com/Path-Check/covid-safe-paths/pull/961

**Comment by johnschoeman** [comment]
@mattThousand or @tparesi could i get a rubber stamp from one of yall on this?

**Review by tparesi — APPROVED** [review]
LGTM

**Pull request merged**
