### PR TITLE
Remove unused bluetooth dependency

### PR DESCRIPTION
**Pull request by mattThousand**
This pull request removes `react-native-ble-advertiser` as a dependency, as well as related infrastructure. Keeping the dependency would mean that we'd request bluetooth entitlements on android for both the `gps` and the `bte` product flavors, which we do not want. 

Since the `Exposure Notifications` APIs will eliminate the need for our own bluetooth/ble implementation, we can remove this dependency.

### CODE REVIEW

**Review by johnschoeman — COMMENTED** [review]
LGTM! no comments.

**Review by tstirrat — APPROVED** [review]

**Comment by tstirrat** [comment]
There are some extra bits in manifest and ios land that might need to be removed?

https://github.com/vitorpamplona/react-native-ble-advertiser#install

**Comment by tstirrat** [comment]
I think its just the Android bits:

```
<uses-permission android:name="android.permission.BLUETOOTH"/>
 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
```

https://github.com/Path-Check/covid-safe-paths/blob/2b346de1bd4d949cc1d95ba469555fc49910207b/android/app/src/main/AndroidManifest.xml#L9-L10

**Comment by mattThousand** [comment]
> I think its just the Android bits:
> 
> ```
> <uses-permission android:name="android.permission.BLUETOOTH"/>
>  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
> ```
> 
> https://github.com/Path-Check/covid-safe-paths/blob/2b346de1bd4d949cc1d95ba469555fc49910207b/android/app/src/main/AndroidManifest.xml#L9-L10

👍 those entitlements were removed from `main/AndroidManifest` in an earlier commit to the target branch:

https://github.com/Path-Check/covid-safe-paths/blob/196a4ebab89b734665250e4385d6d7491bc13c54/android/app/src/main/AndroidManifest.xml#L3

 and the remaining BTE entitlements that we'll need for EN are living in `bte/AndroidManifest`:

https://github.com/Path-Check/covid-safe-paths/blob/196a4ebab89b734665250e4385d6d7491bc13c54/android/app/src/bte/AndroidManifest.xml#L3

**Comment by tstirrat** [comment]
Oh. :) thanks!

**Pull request merged**
