### PR TITLE
Update legal address and link

### PR DESCRIPTION
**Pull request by ericwbailey**
#### Description:

This PR updates the legal address to read "PathCheck Foundation", and updates the URL to `https://covidsafepaths.org/`. [Relevant Trello ticket](https://trello.com/c/gVsmFuDi).

#### Screenshots:

<details>
 <summary>Before</summary>
 ScreenCapture at Tue Jun 23 15:46:36 EDT 2020
</details>

<details>
 <summary>After</summary>
 ScreenCapture at Tue Jun 23 16:40:21 EDT 2020
</details>

#### How to test:

Navigate to More > Legal

### CODE REVIEW

**Review by jeffstolz — APPROVED** [review]

**Review by johnschoeman — APPROVED** [review]
LGTM, as a side note we are using a translation service, Lokalize, so you shouldnt need to update every language manually, as itll eventually make its way through the small translator army Lokalize provides.

Also it looks like you'll need to update the snapshot specs, which you can do with `yarn update-snapshots`

**Comment by ericwbailey** [comment]
Ah cool, good to know! I'll get on both now. Will that help with the failing unit test check?

**Comment by JacobJaffe** [comment]
Just to make sure @ericwbailey , did this get run by design? 

We did a copy review last night on this page, and are about to release for iOS , so that would mean iOS and android have different legal copy

**Comment by JacobJaffe** [comment]
https://pathcheck.atlassian.net/browse/SAF-707

**Comment by ericwbailey** [comment]
@JacobJaffe This update stems from a design audit exercise conducted with Ali last afternoon.

**Review by JacobJaffe — APPROVED** [review]
Confirmed we're good on this

**Pull request merged**
