### PR TITLE
Add automated lokalise import

### PR DESCRIPTION
**Pull request by javierpena**
#### Description:

This commit adds a GitHub action to pull the latest lokalise data and generate a pull request with it. It is scheduled to run every
4 hours.

#### Linked issues:

Fixes SAF-212

#### Screenshots:

<none>

#### How to test:

Once merged, we should see the PR coming/being updated every 4 hours, if any lokalise data has been updated. Alternatively, we could test it by adding "on: \n workflow_dispatch:" to the GitHub workflow definition, so we can run it on demand instead of a fixed schedule.

### CODE REVIEW

**Comment by alpita-masurkar** [comment]
@javierpena This is super! But just remember that there are sometimes errors in translation in Lokalise and sometimes, variables/configurable parameters are not added appropriately inside the translated text in Lokalise. This means that the customizable variable might not show up correctly in those languages. The content should be reviewed for any of these things before such a PR is merged.

**Comment by javierpena** [comment]
@alpita-masurkar thanks for the review.

Sure, this action will always create a PR, which should then be reviewed. It will not merge it on its own.

Maybe I can modify the action configuration, so the commit message states this?

**Comment by alpita-masurkar** [comment]
@javierpena yes, that sounds perfect! thanks once again Javier.

**Comment by javierpena** [comment]
Thanks @alpita-masurkar, I have updated the PR.

**Comment by javierpena** [comment]
So this PR is not getting merged?

**Pull request closed without merging**
