### PR TITLE
Scrypt performance time and staging build settings

### PR DESCRIPTION
**Pull request by MichaelNeas**
#### Description:

This PR will address 2 things:
Adding signpost logs to measure the performance of geohash+scrypt hashing.
Work on the build machines for these failed builds https://github.com/Path-Check/covid-safe-paths/actions?query=workflow%3ABuild+branch%3Adevelop

#### How to test:

View console logs for "org.pathcheck.covid-safepaths" performance category mesurements
The staging machines should successfully build the project.

### CODE REVIEW

**Comment by MichaelNeas** [comment]
@johnschoeman working on getting the build machines up here

**Comment by johnschoeman** [comment]
> @johnschoeman working on getting the build machines up here

Great, thank you!

Note that we are making a push to move all the existing code that cant be included in the bte target build (anything that accesses gps information) to be included only in the GPS target.  Which I think you've done with your new stuff, but wanted to keep you/other readers in the loop.

**Comment by MichaelNeas** [comment]
> > @johnschoeman working on getting the build machines up here
> 
> Great, thank you!
> 
> Note that we are making a push to move all the existing code that cant be included in the bte target build (anything that accesses gps information) to be included only in the GPS target. Which I think you've done with your new stuff, but wanted to keep you/other readers in the loop.

I just noticed your PR, there are 2 build settings you might need to modify with the modifications to the target.  The GPSTests target needs to have the Scrypt library linked in Build Phases > Link with binary libraries > + Scrypt

Screen Shot 2020-06-01 at 2 30 28 PM


Also the Build Target scheme needs to have the App Target added below it

Screen Shot 2020-06-01 at 2 30 02 PM

**Comment by johnschoeman** [comment]
@MichaelNeas 💯 thanks for the help!

**Review by tstirrat — APPROVED** [review]

**Comment by MichaelNeas** [comment]
@tstirrat or @yonatanmk can either of you merge this? I don't have write access

**Comment by johnschoeman** [comment]
@MichaelNeas , locally I am getting this build error for GPSTests
```
        Swift package product 'Scrypt' is linked as a static library by 'GPSTests' and 'GPS'. This will result in duplication of library code.
```

due to having it linked in both the GPS and GPSTests target.
It is required to get the tests to pass in CI however.

Why is it that we need to have Scrypt linked in both targets?

Is there some xcode setting that I need to set to get this build config to work? And should we add that to the readme ? I'm concerned about folk not being able to run the ios tests locally.

**Comment by MichaelNeas** [comment]
@johnschoeman Locally I haven't seen this error on my end.
Maybe it's worth it to nix SPM and make a bridging header for the scrypt C library, as now i'm running into this issue: https://forums.swift.org/t/cannot-using-spm-module-with-some-custom-configuration-not-debug-release-on-xcode-11/26412 on the staging build machine

The target requirement is specifically due to the version of XCode the build machine is on. See this issue: https://github.com/apple/swift-nio/issues/1128 I took a day to figure out how to get it all working, trying a ton of different build settings: https://github.com/Path-Check/covid-safe-paths/pull/919

Before the scheme changes to only have GPS, this was building without error on several different developers xcode environments 😢 And as we can see in the checks in this pr: https://github.com/Path-Check/covid-safe-paths/pull/939/checks?check_run_id=728468599 there's no errors from the doubly linked static libs.

**Comment by johnschoeman** [comment]
@MichaelNeas Got it, it would be nice to have some of the more modern swifty things in, but given the nature of the project we should be doing our best to avoid spinning our wheels if we can. You seem to have a strong swift/ios background so I would defer to you on this one, but if removing SPM helps us get to a stable build process faster I would lean into that.

**Comment by MichaelNeas** [comment]
@johnschoeman I'll definitely throw some time at it this today 😄

**Comment by johnschoeman** [comment]
> @johnschoeman I'll definitely throw some time at it this today 😄

awesome thanks so much for your input!

**Pull request merged**
