### PR TITLE
Haitian Creole missing strings

### PR DESCRIPTION
**Pull request by alpita-masurkar**
#### Description:
There were some strings missing in the last ht commit. Added them.

### CODE REVIEW

**Comment by alpita-masurkar** [comment]
@tstirrat, i can't add you to the review anymore. can you have a look at this and merge this when you have time? Gerald gave these so the strings are reviewed and approved.
Thanks

**Comment by tstirrat** [comment]
Please do not do these here. Do them in lokalise. I cannot keep up with the state of things. I looked for these on lokalise and they are empty for HT on lokalise? Why is that? they'd get overridden on next sync...

**Comment by tstirrat** [comment]
I cant figure out why lokalise has these blank. Please let me know if they were once filled and now are blank *in lokalise*. perhaps something else has broken in the sync.

**Comment by alpita-masurkar** [comment]
@tstirrat Hey, I had filled them in Lokalise as well as created a separate PR here.
Don't know why the ones in Lokalise are blank. But apart from that, there seems to be another miscommunication here. It seemed to me from the conversations on slack that it was decided to do ht strings separately (in a PR) from other strings in lokalise because of the urgency tied with their release. Hence, I did a PR here in addition to the Lokalise. I'm sorry if I didn't understand something correctly.

**Pull request closed without merging**
